
package empmgmnt.gui;

import jdk.nashorn.internal.parser.TokenType;


/**
 *
 * @author dhakadJr
 */
public class OptionFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form OptionFrame1
     */
    public OptionFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrdAddEmp = new javax.swing.JRadioButton();
        jrdSearchEmpl = new javax.swing.JRadioButton();
        jrdShowEmpl = new javax.swing.JRadioButton();
        jrdQuit = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jrdUpdateEmp = new javax.swing.JRadioButton();
        jrdDeleteEmp = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jrdAddEmp.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrdAddEmp);
        jrdAddEmp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jrdAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrdAddEmp.setText("Add Employee");
        jrdAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdAddEmpActionPerformed(evt);
            }
        });

        jrdSearchEmpl.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrdSearchEmpl);
        jrdSearchEmpl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jrdSearchEmpl.setForeground(new java.awt.Color(255, 255, 255));
        jrdSearchEmpl.setText("Search Employee");

        jrdShowEmpl.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrdShowEmpl);
        jrdShowEmpl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jrdShowEmpl.setForeground(new java.awt.Color(255, 255, 255));
        jrdShowEmpl.setText("show All Employee");

        jrdQuit.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrdQuit);
        jrdQuit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jrdQuit.setForeground(new java.awt.Color(255, 255, 255));
        jrdQuit.setText("Quit");

        btnDoTask.setBackground(new java.awt.Color(0, 0, 0));
        btnDoTask.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 255, 255));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Select Your Choice");

        jrdUpdateEmp.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrdUpdateEmp);
        jrdUpdateEmp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jrdUpdateEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrdUpdateEmp.setText("Update Employee");

        jrdDeleteEmp.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrdDeleteEmp);
        jrdDeleteEmp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jrdDeleteEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrdDeleteEmp.setText("Delete Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrdDeleteEmp)
                    .addComponent(jrdAddEmp)
                    .addComponent(btnDoTask)
                    .addComponent(jrdQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrdShowEmpl)
                    .addComponent(jrdSearchEmpl)
                    .addComponent(jrdUpdateEmp))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrdAddEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrdSearchEmpl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrdShowEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrdUpdateEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrdDeleteEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrdQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnDoTask)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrdAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdAddEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdAddEmpActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
        // TODO add your handling code here:
        if (jrdAddEmp.isSelected()) {
            AddEmployeeFrame1 addempfrm=new AddEmployeeFrame1();
            addempfrm.setVisible(true);
            this.dispose();
        }
        else if (jrdShowEmpl.isSelected()) {
            ViewallEmployeeFrame1 viewempl=new ViewallEmployeeFrame1();
            viewempl.setVisible(true);
            this.dispose();
        
        }
        else if (jrdQuit.isSelected()) {
            System.exit(0);
        }
        else if (jrdSearchEmpl.isSelected()) {
            SearchEmployeeFrame1 srchempl=new SearchEmployeeFrame1();
            srchempl.setVisible(true);
            this.dispose();
        }
        else if (jrdUpdateEmp.isSelected()) {
            UpdateEmplFrame up=new UpdateEmplFrame();
            up.setVisible(true);
            this.dispose();
        }
        else{
            DeleteEmpFrame del=new DeleteEmpFrame();
            del.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnDoTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrdAddEmp;
    private javax.swing.JRadioButton jrdDeleteEmp;
    private javax.swing.JRadioButton jrdQuit;
    private javax.swing.JRadioButton jrdSearchEmpl;
    private javax.swing.JRadioButton jrdShowEmpl;
    private javax.swing.JRadioButton jrdUpdateEmp;
    // End of variables declaration//GEN-END:variables
}
